USE SCEcommerceDB
GO

IF NOT EXISTS(SELECT TOP 1 TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Category')
BEGIN
	CREATE TABLE Category
	(
		Id INT PRIMARY KEY IDENTITY (1,1),
		[Name] NVARCHAR (30),
		[Description] NVARCHAR (100),
		[Image] NVARCHAR(MAX)
	)
END